### ISSUE TITLE
raw input issue

### ISSUE THREAD

**Issue by Pakogrande** [Ranarrr/rN#1]
why can i lj with this and he can't? when he tries to lj hes just spinning around in a circle? 
what may be the issue?

**Comment by Ranarrr** [comment]
Thats the issue of raw input, when raw input is enabled it will spin around as soon as you activate it and is above ground<strike>, im sorry, not much i can do about it (need to recode some parts, dont feel like doing it anytime soon), tell him to deactivate it in cs.</strike>

**Comment by Ranarrr** [comment]
Closed as i fixed it.
